HOST: https://q.quanti.cz/api/v1

--- Quanti - Mailing V1 Resources ---

---
Mailing is the web application project for Quanti Ltd company. 

- Data are taken and provided only in the format **application/json**! 
- If an error occurs, the API returns the error description and sets the **HTTP (4xx) code**. 
- Each request must be set the **Content-Type** header with the value of **application/json**. 
- The decimal separator is a **period** (not a comma!).
- When sending a request, you MUST always check that the server returned **HTTP response code 2xx**. If the code is different, the request was not processed successfully. 
- Each request (except authentication) must be sent with the **X-Api-Key header**. For getting the value for your company, please, contact support@mailq.cz
- DateTimes are specified in the **ISO 8601** format.
- Use only the **UTF-8** encoding.
---

--
Customer Resources
--
Gets all Customer entries with its SenderEmail entries for current user
GET /customers/current
> Accept: application/json
> X-Api-Key: abcd
< 200
< Content-Type: application/json
[
    { "id": 2,
      "name": "Second Customer",
      "senderEmails": [
          {"id": 4, "senderEmail": "secondcustomer@quanti.sk"},
          {"id": 3, "senderEmail": "secondcustomer@quanti.cz"}
       ]
    },
    { "id": 1,
      "name": "First Customer",
      "senderEmails": [
          {"id": 1, "senderEmail": "firsrtcustomer@quanti.cz"},
          {"id": 2, "senderEmail": "firsrtcustomer@quanti.sk"}
       ]      
    }
]
+++++
< 400
< Content-Type: application/json
{
    "error": {
        "code": 123,
        "message": "Wrong entity data",
        "developerMessage": "Wrong entity data in blablabla"
    }
}
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification Email Status Resources
--

Get list of possible Notification email statuses
GET /mails/email-statuses
> Accept: application/json
> X-Api-Key: abcd
< 200
< Content-Type: application/json
{
  "emailStatuses": [
    "OK",
    "INVALID_ADDRESS",
    "UNRESOLVED_MX",
    "UNKNOWN_ERROR",
    "UNSUBSCRIBED",
    "PREVIOUSLY_UNDELIVERED",
    "UNSENT"
  ]
}
+++++
< 400
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503


--
Notification Email Postfix Message Resources
--

Get list of possible Email postfix messages
GET /mails/postfix-messages
> Accept: application/json
> X-Api-Key: abcd
< 200
< Content-Type: application/json
{
  "postfixMessages": [
    "NEW",
    "SENT",
    "DELIVERED",
    "ERROR",
    "ABORTED",
    "DEFERRED",
    "DEFERRED_GREYLISTING",
    "DEFAULT",
    "UNSENT"
  ]
}
+++++
< 400
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503


--
Notification Status Resources
--

Get list of possible Notification statuses
GET /mails/statuses
> Accept: application/json
> X-Api-Key: abcd
< 200
< Content-Type: application/json
{
  "statuses": [
    "READY",
    "FINISHED"
  ]
}
+++++
< 400
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503


--
Notification Resources
Notification API is used for managing transactional emails
--

Creates Notification
POST /mails
> Content-Type: application/json
> Accept: application/json
> X-Api-Key: abcd
{ 
    "customer": "Second Customer", 
    "senderEmail": "secondcustomer@quanti.cz", 
    "name": "Test", 
    "code": "ABCD", 
    "text": base64Encode("Alternative email text"),
    "template": base64Encode("<html><body>...."),
    "ampTemplate": base64Encode("<html amp><body>....")
 }
< 201
< Content-Type: application/json
< Location: /mails/{id}
{ 
    "id": "e611021c-51d2-43df-87c9-f0a9d31504ea",
    "name": "Test"
    "code": "qqq"
    "text": "Alternative email text",
    "template": "YWxlbHVqYQ==",
    "ampTemplate": "YWxlbHVqYQ==",
    "appliedSenderEmail": "firsrtcustomer@quanti.cz"
 }
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 409
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


Updates Notification
PUT /mails/{id}
> Content-Type: application/json
> Accept: application/json
> X-Api-Key: abcd
{ 
    "customer": "Second Customer", 
    "senderEmail": "secondcustomer@quanti.cz", 
    "name": "Test", 
    "code": "ABCD", 
    "text": base64Encode("Alternative email text"),
    "template": base64Encode("<html><body>...."),
    "ampTemplate": base64Encode("<html amp><body>....")
 }
< 204
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 409
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


Get Notification by id
GET /mails/{id}
> Accept: application/json
> X-Api-Key: abcd
< 200
< Content-Type: application/json
{
    "id": "e611021c-51d2-43df-87c9-f0a9d31504ea",
    "name": "Test"
    "code": "qqq"
    "text": "Alternative email text",
    "template": "YWxlbHVqYQ==",
    "ampTemplate": "YWxlbHVqYQ==",
    "appliedSenderEmail": "firsrtcustomer@quanti.cz"
}
+++++
< 400
< Content-Type: application/json
{
    "error": {
        "code": 123,
        "message": "Wrong entity data",
        "developerMessage": "Wrong entity data in blablabla"
    }
}
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


Deletes Notification if it was not processed yet
DELETE /mails/{id}
> Accept: application/json
< 204
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification Email Resources
--

Creates Email entry for sending mail to user
POST /mails/{id}/data
> Content-Type: application/json
> Accept: application/json
> X-Api-Key: abcd
{ 
    "recipientEmail": "secondcustomer@quanti.cz", 
    "replyToEmail": "reply-to@email.com",
    "dateFrom": "2014-06-19T06:00:00.000",
    "data": {
        "osloveni": "Bacos zdar",
        "sloveso": "rekl"
    },
    "cc": [
        "ccemail@quanti.cz"
    ],
    "bcc": [
        "bccemail@quanti.cz"
    ],
    "attachments":[
        {
            "displayName": "Priloha 1",
            "link": null,
            "source": "base64text",
            "mimeType": "text/plain"
        },
        {
            "displayName": "Priloha 2",
            "link": "odkaz na zdroj",
            "source": "base64text",
            "mimeType": "image/jpeg"
        }
    ]
 }
< 201
< Content-Type: application/json
< Location: /mails/{id}/data/{dataId}
{
    "id": "e611021c-51d2-43df-87c9-f0a9d31504ea",
    "email": "secondcustomer@quanti.cz",
    "replyToEmail": "reply-to@email.com",
    "created": "2014-09-11T16:02:27.761+02:00",
    "openedTimestamp": "2014-09-11T17:02:27.761+02:00",
    "undeliveredTimestamp": null,
    "cc": [
        "ccemail@quanti.cz"
    ],
    "bcc": [
        "bccemail@quanti.cz"
    ],
    "data": {
        "osloveni":"Bacos zdar",
        "sloveso":"rekl"
    },
    "attachments":[
        {
            "displayName": "Priloha 1",
            "fileName": "attachment--0000-2222-3333-4444",
            "link": "http://img.quanti.cz/obr1.png",
            "mimeType": "text/plain"
        },
        {
            "displayName": "Priloha 2",
            "fileName": "attachment--1111-2222-3333-4444",
            "link": "http://img.quanti.cz/obr2.png",
            "mimeType": "image/jpeg"
        }
    ],
    "emailStatus": "OK",
    "postfixMessage": "DELIVERED"
}
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 409
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


Get Notification Emails
GET /mails/{id}/data
> Accept: application/json
> X-Api-Key: abcd
[
    {
        "id": "e611021c-51d2-43df-87c9-f0a9d31504ea",
        "email": "secondcustomer@quanti.cz",
        "replyToEmail": "reply-to@email.com",
        "created": "2014-09-11T16:02:27.761+02:00",
        "openedTimestamp": "2014-09-11T17:02:27.761+02:00",
        "undeliveredTimestamp": null,
        "cc": [
            "ccemail@quanti.cz"
        ],
        "bcc": [
            "bccemail@quanti.cz"
        ],
        "data": {
            "osloveni":"Bacos zdar",
            "sloveso":"rekl"
        },
        "attachments":[
            {
                "displayName": "Priloha 1",
                "fileName": "attachment--0000-2222-3333-4444",
                "link": "http://img.quanti.cz/obr1.png",
                "mimeType": "text/plain"
            },
            {
                "displayName": "Priloha 2",
                "fileName": "attachment--1111-2222-3333-4444",
                "link": "http://img.quanti.cz/obr2.png",
                "mimeType": "image/jpeg"
            }
        ],
        "emailStatus": "OK",
        "postfixMessage": "DELIVERED"
    }
]
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


Get Notification Email
GET /mails/{id}/data/{id}
> Accept: application/json
> X-Api-Key: abcd
{
    "id": "e611021c-51d2-43df-87c9-f0a9d31504ea",
    "email": "secondcustomer@quanti.cz"
    "replyToEmail": "reply-to@email.com",
    "created": "2014-09-11T16:02:27.761+02:00",
    "openedTimestamp": "2014-09-11T17:02:27.761+02:00",
    "undeliveredTimestamp": null,
    "cc": [
        "ccemail@quanti.cz"
    ],
    "bcc": [
        "bccemail@quanti.cz"
    ],
    "data": {
        "osloveni":"Bacos zdar",
        "sloveso":"rekl"
    },
    "attachments":[
        {
            "displayName": "Priloha 1",
            "fileName": "attachment--0000-2222-3333-4444",
            "link": "http://img.quanti.cz/obr1.png",
            "mimeType": "text/plain"
        },
        {
            "displayName": "Priloha 2",
            "fileName": "attachment--1111-2222-3333-4444",
            "link": "http://img.quanti.cz/obr2.png",
            "mimeType": "image/jpeg"
        }
    ],
    "emailStatus": "OK",
    "postfixMessage": "DELIVERED"
}
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification history Resources
--

Get all Notification history, type filter parameter one of opened/delivered/undelivered
GET /mails/{id}/history/?type={type}&from={from}&to={to}&limit={limit}&offset={offset}
> Accept: application/json
> X-Api-Key: abcd
[{
    "id": "e611021c-51d2-43df-87c9-f0a9d31504ea",
    "email": "secondcustomer@quanti.cz"
    "replyToEmail": "reply-to@email.com",
    "created": "2014-09-11T16:02:27.761+02:00",
    "openedTimestamp": "2014-09-11T17:02:27.761+02:00",
    "undeliveredTimestamp": null,
    "cc": [
        "ccemail@quanti.cz"
    ],
    "bcc": [
        "bccemail@quanti.cz"
    ],
    "data": {
        "osloveni":"Bacos zdar",
        "sloveso":"rekl"
    },
    "attachments":[
        {
            "displayName": "Priloha 1",
            "fileName": "attachment--0000-2222-3333-4444",
            "link": "http://img.quanti.cz/obr1.png",
            "mimeType": "text/plain"
        },
        {
            "displayName": "Priloha 2",
            "fileName": "attachment--1111-2222-3333-4444",
            "link": "http://img.quanti.cz/obr2.png",
            "mimeType": "image/jpeg"
        }
    ],
    "emailStatus": "OK",
    "postfixMessage": "DELIVERED"
},
{
    "id": "0dce3e4f-66ca-4d8d-a777-f87c402b1608",
    "email": "thirdcustomer@quanti.cz"
    "replyToEmail": "reply-to@email.com",
    "created": "2014-09-11T16:02:27.761+02:00",
    "openedTimestamp": "2014-09-11T17:02:27.761+02:00",
    "undeliveredTimestamp": null,
    "cc": [
        "ccemail@quanti.cz"
    ],
    "bcc": [
        "bccemail@quanti.cz"
    ],
    "data": {
        "osloveni":"Bacos zdar",
        "sloveso":"rekl"
    },
    "attachments":[
        {
            "displayName": "Priloha 1",
            "fileName": "attachment--0000-2222-3333-4444",
            "link": "http://img.quanti.cz/obr1.png",
            "mimeType": "text/plain"
        },
        {
            "displayName": "Priloha 2",
            "fileName": "attachment--1111-2222-3333-4444",
            "link": "http://img.quanti.cz/obr2.png",
            "mimeType": "image/jpeg"
        }
    ],
    "emailStatus": "OK",
    "postfixMessage": "DELIVERED"
}]
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification Email history Resources
--

Get Recipient email history for specific Notification
GET /mails/{id}/history/{email}?limit={limit}&offset={offset}
> Accept: application/json
> X-Api-Key: abcd
[{
    "id": "e611021c-51d2-43df-87c9-f0a9d31504ea",
    "email": "secondcustomer@quanti.cz"
    "replyToEmail": "reply-to@email.com",
    "created": "2014-09-11T16:02:27.761+02:00",
    "openedTimestamp": "2014-09-11T17:02:27.761+02:00",
    "undeliveredTimestamp": null,
    "cc": [
        "ccemail@quanti.cz"
    ],
    "bcc": [
        "bccemail@quanti.cz"
    ],
    "data": {
        "osloveni":"Bacos zdar",
        "sloveso":"rekl"
    },
    "attachments":[
        {
            "displayName": "Priloha 1",
            "fileName": "attachment--0000-2222-3333-4444",
            "link": "http://img.quanti.cz/obr1.png",
            "mimeType": "text/plain"
        },
        {
            "displayName": "Priloha 2",
            "fileName": "attachment--1111-2222-3333-4444",
            "link": "http://img.quanti.cz/obr2.png",
            "mimeType": "image/jpeg"
        }
    ],
    "emailStatus": "OK",
    "postfixMessage": "DELIVERED"
},
{
    "id": "0dce3e4f-66ca-4d8d-a777-f87c402b1608",
    "email": "secondcustomer@quanti.cz"
    "replyToEmail": "reply-to@email.com",
    "created": "2014-09-11T16:02:27.761+02:00",
    "openedTimestamp": "2014-09-11T17:02:27.761+02:00",
    "undeliveredTimestamp": null,
    "cc": [
        "ccemail@quanti.cz"
    ],
    "bcc": [
        "bccemail@quanti.cz"
    ],
    "data": {
        "osloveni":"Bacos zdar",
        "sloveso":"rekl"
    },
    "attachments":[
        {
            "displayName": "Priloha 1",
            "fileName": "attachment--0000-2222-3333-4444",
            "link": "http://img.quanti.cz/obr1.png",
            "mimeType": "text/plain"
        },
        {
            "displayName": "Priloha 2",
            "fileName": "attachment--1111-2222-3333-4444",
            "link": "http://img.quanti.cz/obr2.png",
            "mimeType": "image/jpeg"
        }
    ],
    "emailStatus": "OK",
    "postfixMessage": "DELIVERED"
}]
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification Statistics Resources
--

Get Statistics for specific Notification
GET /mails/{id}/statistics?from={from}&to={to}
> Accept: application/json
> X-Api-Key: abcd
{
     "sent": 9,
     "delivered": 9,
     "opened": 7
}
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification Opened Emails Statistics Resources
--

Get Opened Emails Statistics for specific Notification
GET /mails/{id}/opened-emails?from={from}&to={to}&limit={limit}&offset={offset}
> Accept: application/json
> X-Api-Key: abcd
[
    {
         "email": "info@firma.cz",
         "openedTimestamp": "2014-06-06T16:39:34+02:00"
    },
    {
         "email": "newsletter@mailq.cz",
         "openedTimestamp": "2014-06-06T16:39:34+02:00"
    }
]
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification Unsent Emails Statistics Resources
--

Get Unsent Emails Statistics for specific Notification
GET /mails/{id}/unsent-emails?from={from}&to={to}&limit={limit}&offset={offset}
> Accept: application/json
> X-Api-Key: abcd
[
    {
         "email": "info@firma.cz",
         "reason": "INVALID_ADDRESS"
    },
    {
         "email": "newsletter@mailq.cz",
         "reason": "UNRESOLVED_MX"
    }
]
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json


--
Notification Undelivered Emails Statistics Resources
--

Get Undelivered Emails Statistics for specific Notification
GET /mails/{id}/undelivered-emails?from={from}&to={to}&limit={limit}&offset={offset}
> Accept: application/json
> X-Api-Key: abcd
[
    {
         "email": "info@firma.cz",
         "reason": "DEFERRED"
    },
    {
         "email": "newsletter@mailq.cz",
         "reason": "ERROR"
    }
]
< 200
< Content-Type: application/json
+++++
< 401
< Content-Type: application/json
+++++
< 403
< Content-Type: application/json
+++++
< 405
< Content-Type: application/json
+++++
< 406
< Content-Type: application/json
+++++
< 500
< Content-Type: application/json
+++++
< 503
< Content-Type: application/json
